### PR TITLE
improve key handling for CAK7 and overcrypt keys

### PR DESCRIPTION
**Pull request by WXbet**

### CODE REVIEW

**Comment by ghost** [comment]
```
#include <stdio.h>
#include <stdint.h>
#include <string.h>

///////////////////////////////////////////////////////////////////////////////////////
// last +1 val = 0x01 (ins7E, mod1, mod2, key3588, data50, mod50, nuid, cwpk)
// https://github.com/Schimmelreiter/oscam-smod/blob/master/oscam-config-reader.c#L457
//                 8 or 16 bytes
// last +1 val = 0x08, 0x10 (k1_generic, k1_unique)
// https://github.com/Schimmelreiter/oscam-smod/blob/master/oscam-config-reader.c#L484
///////////////////////////////////////////////////////////////////////////////////////


int main() {
                                       //null: strlen=2
static uint8_t key[16 + 1] = {0x01,0x02,0x00,0x04,0x05,0x06,0x07,0x08,0x09,0x10,0x11,0x12,0x13,0x14,0x15,0x16};
printf("key: ");
for(int32_t i = 0; i < sizeof(key) ; i++) { printf("%02X", key[i]); }
printf(" \nstrlen: %ld sizeof: %ld \n", strlen((char*)key), sizeof(key));

if (key[16] != 0x10) //16 bytes
printf("(+1) invalid\n");
}
```
out: 
key: 0102000405060708091011121314151600 
strlen: 2 sizeof: 17 
(+1) invalid

**Comment by WXbet** [comment]
strlen=2, Why?
I‘ve tested the commit with several keys and then strlen value seems to be okay.

**Comment by WXbet** [comment]
Okay, strlen is looking for 0 value. Your key has 0 on Pos 3. My Testkeys has no 0 inside. You are right, the commit is invalid.

**Comment by ghost** [comment]
```
#include <stdio.h>
#include <stdint.h>
#include <string.h>

///////////////////////////////////////////////////////////////////////////////////////
// last +1 val = 0x01 (ins7E, mod1, mod2, key3588, data50, mod50, nuid, cwpk)
// https://github.com/Schimmelreiter/oscam-smod/blob/master/oscam-config-reader.c#L457
//                 8 or 16 bytes
// last +1 val = 0x08, 0x10 (k1_generic, k1_unique)
// https://github.com/Schimmelreiter/oscam-smod/blob/master/oscam-config-reader.c#L484
///////////////////////////////////////////////////////////////////////////////////////


int main() {                      // and unfortunately this key has more 0 values
static uint8_t ins7E[0x1A + 1] = {0x01,0x00,0x03,0x04,0x00,0x00,0x00,0x00,0x09,0x10,0x11,0x12,0x00,0x00,0x00,0x00,0x00,0x18,0x19,0x20,0x21,0x00,0x23,0x24,0x25,0x26};
printf("ins7E key: ");
for(int32_t i = 0; i < sizeof(ins7E) ; i++) { printf("%02X", ins7E[i]); }
printf(" \nstrlen: %ld sizeof: %ld \n", strlen((char*)ins7E), sizeof(ins7E));
if (!ins7E[26])
printf("key is invalid!!!\n");
}

```
out:
ins7E key: 010003040000000009101112000000000018192021002324252600 
strlen: 1 sizeof: 27 
key is invalid!!!

**Comment by WXbet** [comment]
You are right. strlen looks for the first occurance of 0. so the length does not fit our needs. I submit a better PR later this day.

**Comment by WXbet** [comment]
strlen looks for the first occurance of 0. so the length calculation is invalid. I submit a better PR later this day.

**Pull request closed without merging**
